spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=GMT
    hikari:
      username: root
      password: hwq2019
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        #        指定nacos 服务器地址
        server-addr: localhost:8848
        cluster-name: beijing
    sentinel:
      transport:
        #        制定sentinel控制台地址
        dashboard: localhost:8080
      web-context-unify: false
      filter:
        #        打开对springMvc端点的保护
        enabled: true
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          output:
            producer:
#              表明是事务消息
              transactional: true
              group: user-center-group
          alterTransaction:
            producer:
              transactional: true
              group: alter-transaction-group
      bindings:
        output:
          #          用来指定topic
          destination: transaction-stock
        alterTransaction:
          destination: alter-transaction
  application:
    #    不要用下划线和特殊字符
    name: user-center
  #    允许相同对象的feignClient一起启动
  main:
    allow-bean-definition-overriding: true
  zipkin:
    base-url: http://localhost:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
#      抽样率
      probability: 1.0


server:
  port: 8070

commodity-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.mall.user_center.configuration.NacosSameClusterWeightedRule

ribbon:
  eager-load:
    enabled: true
    clients: commodity-center

logging:
  level:
    com.mall.user_center.feignClient.CommodityCenterFeignClient: debug

feign:
  #  feign 整合sentinel
  sentinel:
    enabled: true
  client:
    config:
      #      全局配置为将服务名称改为default
#      default:
#        requestInterceptors:
#          - com.mall.user_center.feignClient.interceptor.TokenRelayRequestInterceptor
      commodity-center:
        loggerLevel: full
        requestInterceptors:
          - com.mall.user_center.feignClient.interceptor.TokenRelayRequestInterceptor
  #        让feign使用httpClient做请求
  httpclient:
    enabled: true
    #    feign 最大连接数
    max-connections: 200
    #    单个url最大连接数
    max-connections-per-route: 50
#将actuator端点暴露出
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
#关闭restTemplate整合sentinel
resttemplate:
  sentinel:
    enabled: false
#  rocketmq自己配置
#rocketmq:
#  name-server: 127.0.0.1:9876
#  producer:
#    group: test-group
#    send-message-timeout: 50000
jwt:
  secret: qwertyuiopasdfghjkl
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600

